apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pleasant-piranha-disk
  namespace: beehive-virtual-machines
  annotations:
    cdi.kubevirt.io/storage.import.sourceName: pleasant-import-source
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeImportSource
    name: pleasant-import-source
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 30Gi
